setConf TZ_REPORT_ACT 0
setConf RTL_FSDB ../../cpu/novas.fsdb
setConf EXPORT_PARASITIC 1
setConf PPRTL_RUN_COMPLETED ""
setConf EXPORT_CELL_COORDS 0
setConf LINK_LIBRARY ""
setConf DESIGN_NAME cpu
setConf SELF_CONTAINED_WORKSPACE 0
setConf FUSION_LEF_FILES ""
setConf TZ_COMPILE_CMDS ""
setConf RTL_SAIF ""
setConf TZ_SETUP_CMDS ""
setConf ELABORATED_BLOCK ""
setConf RTLA_VERSION V-2023.12-SP5-3
setConf MCMM_FLOW 1
setConf BLOCK_INSTANCES ""
setConf NCORES 8
setConf FSDB_SYSVER 0
setConf ZZ_SETUP_CMDS ""
setConf BLOCK_WORKSPACES ""
setConf RESTORE_VAR_STATE 0
setConf MERGE_SAIF_OPT ""
setConf ZZ_SETUP ""
setConf REPORT 0
setConf RTL_VCD ""
setConf AZ_SETUP_CMDS ""
setConf PP_POSTCMD ""
setConf TECH_LIB ""
setConf SDC_SETUP ""
setConf RUN_ON_ELAB 0
setConf SCENARIO func@nominal
setConf BACKUP_LIBRARY_NAMES ""
setConf EXPORT_CG_INFO 0
setConf MODULE_NAME ""
setConf REF_LIBS ""
setConf PPRTL_VERSION ""
setConf IMPORT_XREF 1
setConf ACTIVITY_FILE_PATH ""
setConf HIER_NDM_READ 0
setConf CORNER ""
setConf FUSION_LIB 0
setConf EXIT_AFTER ""
setConf COPY_LIB_REFLIB 0
setConf FSDB_TIME ""
setConf REMOVE_EXISTING_OUTPUT_DIR 0
setConf EXPORT_CONSTRAINT 1
setConf PP_SHELL pwr_shell
setConf RTLA_RUN_COMPLETED 1
setConf FUSION_LIB_FILES ""
setConf CREATE_LIB_OPT ""
setConf PP_PRE_PWR_CMDS ""
setConf SDPD_CELLS ""
setConf INSTANCE_NAME ""
setConf PRE_SYNTH_EXIT 0
setConf DISABLE_HARD_ERRORS 0
setConf STRIP_PATH cpu_tb/cpu_inst
setConf EVENT_SHIFT 0
setConf PP_SETUP ""
setConf SKIP_GPD 0
setConf COPY_LIB_DESIGN 0
setConf SEARCH_PATH ""
setConf TECH_FILE ""
setConf PHYSICAL_LESS_FUSION_LIB 0
setConf EXPORT_UPF 1
setConf RTL_LIST_FILE ""
setConf MODE ""
setConf TZ_SHELL tz_shell
setConf POWERLIB_ONLY 0
setConf FAST_CGE_MODE 0
setConf IGNORE_VERSION_CHECKS 0
setConf EXTENDED_NAME /storage/e19129/projects/e19-co502-RV32IM-Pipeline-Implementation-Group1/synopsys/cpu_sky130_fd_sc_hd/cpu_LIB:cpu.design
setConf KEEP_PHYSICAL_ONLY 0
setConf COPY_LIB_BLOCK 0
setConf EXPORT_MODULE_CELL_MAP 1
setConf EXPORT_MAPPING 1
setConf PP_DBFLOW 0
setConf FUSION_TECH_FILE ""
setConf TZ_SETUP ""
setConf CURRENT_SCENARIO func@nominal
setConf USE_SPEF 0
setConf AZ_SETUP ""
setConf RTL_FILES ""
setConf REF_FLIBS ""
setConf RTL_LIST_FILE_TYPE ""
setConf PP_PRE_PWR_SETUP ""
setConf LC_SHELL lc_shell
setConf ESSENTIAL_NAMEMAP 1
setConf READ_ACT_CMD ""
setConf OUTPUT_DIR TZ_OUTDIR
