set_property SRC_FILE_INFO {cfile:/home/katta/fyp/RISC_CPU/RISC_CPU.srcs/constrs_1/new/cpuXDC.xdc rfile:../../../RISC_CPU.srcs/constrs_1/new/cpuXDC.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN H19 [get_ports CLK_GEN]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AV40 [get_ports RST]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AM39 [get_ports CLK]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AN39 [get_ports CPU_ACTIVE]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR37 [get_ports REG_WRITE]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AT37 [get_ports MEM_ACCESS]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AR35 [get_ports BRANCH_TAKEN]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP41 [get_ports HAZARD_DETECTED]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AP42 [get_ports PC_out]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN AU39 [get_ports INST_out]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[6]}]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[3]}]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[0]}]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[1]}]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[2]}]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[4]}]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[5]}]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[7]}]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[8]}]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[9]}]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[10]}]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[16]}]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[17]}]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[14]}]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[20]}]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[21]}]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[18]}]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[24]}]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[25]}]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[22]}]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[23]}]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[19]}]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[15]}]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[11]}]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[12]}]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[13]}]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[26]}]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[27]}]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[28]}]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[29]}]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[30]}]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/ALU_OUT_EX[31]}]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][6]}]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][2]}]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][0]}]
set_property src_info {type:XDC file:1 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][1]}]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][3]}]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][4]}]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][5]}]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][11]}]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][12]}]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][7]}]
set_property src_info {type:XDC file:1 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][8]}]
set_property src_info {type:XDC file:1 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][15]}]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][16]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][13]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][19]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][20]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][17]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][18]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][14]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][9]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][10]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][26]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][22]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][21]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][23]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][24]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][25]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][31]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][27]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][28]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][29]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/instr_out_reg[31][30]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[13]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[5]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[0]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[1]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[2]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[3]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[4]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[6]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[7]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[14]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[15]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[12]}]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[18]}]
set_property src_info {type:XDC file:1 line:120 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[19]}]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[16]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[22]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[23]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[20]}]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[26]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[27]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[24]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[30]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[31]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[28]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[29]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[25]}]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[21]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[17]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[8]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[9]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[10]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/pc_out[11]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[9]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[4]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[0]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[1]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[2]}]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[3]}]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[5]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[6]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[7]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[8]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[11]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[17]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[18]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[15]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[21]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[22]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[19]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[25]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[26]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[23]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[29]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[30]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[27]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[31]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[28]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[24]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[20]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[16]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[12]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[13]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[14]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/D[10]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[14]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[6]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[2]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[0]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[1]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[3]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[4]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[5]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[11]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[12]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[7]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[8]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[15]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[16]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[13]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[19]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[20]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[17]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[23]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[24]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[21]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[27]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[28]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[25]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[31]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[29]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[30]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[26]}]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[22]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[18]}]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[9]}]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[1]_30[10]}]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[14]}]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[6]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[2]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[0]}]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[1]}]
set_property src_info {type:XDC file:1 line:208 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[3]}]
set_property src_info {type:XDC file:1 line:209 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[4]}]
set_property src_info {type:XDC file:1 line:210 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[5]}]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[11]}]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[12]}]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[7]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[8]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[15]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[16]}]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[13]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[19]}]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[20]}]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[17]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[23]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[24]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[21]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[27]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[28]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[25]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[31]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[29]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[30]}]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[26]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[22]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[18]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[9]}]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[2]_29[10]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[14]}]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[6]}]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[2]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[0]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[1]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[3]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[4]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[5]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[11]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[12]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[7]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[8]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[15]}]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[16]}]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[13]}]
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[19]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[20]}]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[17]}]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[23]}]
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[24]}]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[21]}]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[27]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[28]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[25]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[31]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[29]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[30]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[26]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[22]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[18]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[9]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[3]_28[10]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[6]}]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[2]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[0]}]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[1]}]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[3]}]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[4]}]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[5]}]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[11]}]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[12]}]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[7]}]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[8]}]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[15]}]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[16]}]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[13]}]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[14]}]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[9]}]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[10]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[22]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[18]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[17]}]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[19]}]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[20]}]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[21]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[27]}]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[28]}]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[23]}]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[24]}]
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[25]}]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[31]}]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[29]}]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[30]}]
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[4]_27[26]}]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[14]}]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[6]}]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[2]}]
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[0]}]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[1]}]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[3]}]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[4]}]
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[5]}]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[11]}]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[12]}]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[7]}]
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[8]}]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[15]}]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[16]}]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[13]}]
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[19]}]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[20]}]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[17]}]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[23]}]
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[24]}]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[21]}]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[27]}]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[28]}]
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[25]}]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[31]}]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[29]}]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[30]}]
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[26]}]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[22]}]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[18]}]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[9]}]
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[5]_26[10]}]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[14]}]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[6]}]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[2]}]
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[0]}]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[1]}]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[3]}]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[4]}]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[5]}]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[11]}]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[12]}]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[7]}]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[8]}]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[15]}]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[16]}]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[13]}]
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[19]}]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[20]}]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[17]}]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[23]}]
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[24]}]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[21]}]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[27]}]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[28]}]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[25]}]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[31]}]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[29]}]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[30]}]
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[26]}]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[22]}]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[18]}]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[9]}]
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[6]_25[10]}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[14]}]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[6]}]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[2]}]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[0]}]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[1]}]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[3]}]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[4]}]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[5]}]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[11]}]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[12]}]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[7]}]
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[8]}]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[15]}]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[16]}]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[13]}]
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[19]}]
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[20]}]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[17]}]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[23]}]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[24]}]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[21]}]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[27]}]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[28]}]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[25]}]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[31]}]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[29]}]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[30]}]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[26]}]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[22]}]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[18]}]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[9]}]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {cpu_inst/reg_files_inst/mem_reg[7]_24[10]}]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 131072 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list CLK_GEN_IBUF_BUFG]]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {cpu_inst/reg_files_inst/mem_reg[1]_30[0]} {cpu_inst/reg_files_inst/mem_reg[1]_30[1]} {cpu_inst/reg_files_inst/mem_reg[1]_30[2]} {cpu_inst/reg_files_inst/mem_reg[1]_30[3]} {cpu_inst/reg_files_inst/mem_reg[1]_30[4]} {cpu_inst/reg_files_inst/mem_reg[1]_30[5]} {cpu_inst/reg_files_inst/mem_reg[1]_30[6]} {cpu_inst/reg_files_inst/mem_reg[1]_30[7]} {cpu_inst/reg_files_inst/mem_reg[1]_30[8]} {cpu_inst/reg_files_inst/mem_reg[1]_30[9]} {cpu_inst/reg_files_inst/mem_reg[1]_30[10]} {cpu_inst/reg_files_inst/mem_reg[1]_30[11]} {cpu_inst/reg_files_inst/mem_reg[1]_30[12]} {cpu_inst/reg_files_inst/mem_reg[1]_30[13]} {cpu_inst/reg_files_inst/mem_reg[1]_30[14]} {cpu_inst/reg_files_inst/mem_reg[1]_30[15]} {cpu_inst/reg_files_inst/mem_reg[1]_30[16]} {cpu_inst/reg_files_inst/mem_reg[1]_30[17]} {cpu_inst/reg_files_inst/mem_reg[1]_30[18]} {cpu_inst/reg_files_inst/mem_reg[1]_30[19]} {cpu_inst/reg_files_inst/mem_reg[1]_30[20]} {cpu_inst/reg_files_inst/mem_reg[1]_30[21]} {cpu_inst/reg_files_inst/mem_reg[1]_30[22]} {cpu_inst/reg_files_inst/mem_reg[1]_30[23]} {cpu_inst/reg_files_inst/mem_reg[1]_30[24]} {cpu_inst/reg_files_inst/mem_reg[1]_30[25]} {cpu_inst/reg_files_inst/mem_reg[1]_30[26]} {cpu_inst/reg_files_inst/mem_reg[1]_30[27]} {cpu_inst/reg_files_inst/mem_reg[1]_30[28]} {cpu_inst/reg_files_inst/mem_reg[1]_30[29]} {cpu_inst/reg_files_inst/mem_reg[1]_30[30]} {cpu_inst/reg_files_inst/mem_reg[1]_30[31]}]]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:448 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {cpu_inst/reg_files_inst/mem_reg[2]_29[0]} {cpu_inst/reg_files_inst/mem_reg[2]_29[1]} {cpu_inst/reg_files_inst/mem_reg[2]_29[2]} {cpu_inst/reg_files_inst/mem_reg[2]_29[3]} {cpu_inst/reg_files_inst/mem_reg[2]_29[4]} {cpu_inst/reg_files_inst/mem_reg[2]_29[5]} {cpu_inst/reg_files_inst/mem_reg[2]_29[6]} {cpu_inst/reg_files_inst/mem_reg[2]_29[7]} {cpu_inst/reg_files_inst/mem_reg[2]_29[8]} {cpu_inst/reg_files_inst/mem_reg[2]_29[9]} {cpu_inst/reg_files_inst/mem_reg[2]_29[10]} {cpu_inst/reg_files_inst/mem_reg[2]_29[11]} {cpu_inst/reg_files_inst/mem_reg[2]_29[12]} {cpu_inst/reg_files_inst/mem_reg[2]_29[13]} {cpu_inst/reg_files_inst/mem_reg[2]_29[14]} {cpu_inst/reg_files_inst/mem_reg[2]_29[15]} {cpu_inst/reg_files_inst/mem_reg[2]_29[16]} {cpu_inst/reg_files_inst/mem_reg[2]_29[17]} {cpu_inst/reg_files_inst/mem_reg[2]_29[18]} {cpu_inst/reg_files_inst/mem_reg[2]_29[19]} {cpu_inst/reg_files_inst/mem_reg[2]_29[20]} {cpu_inst/reg_files_inst/mem_reg[2]_29[21]} {cpu_inst/reg_files_inst/mem_reg[2]_29[22]} {cpu_inst/reg_files_inst/mem_reg[2]_29[23]} {cpu_inst/reg_files_inst/mem_reg[2]_29[24]} {cpu_inst/reg_files_inst/mem_reg[2]_29[25]} {cpu_inst/reg_files_inst/mem_reg[2]_29[26]} {cpu_inst/reg_files_inst/mem_reg[2]_29[27]} {cpu_inst/reg_files_inst/mem_reg[2]_29[28]} {cpu_inst/reg_files_inst/mem_reg[2]_29[29]} {cpu_inst/reg_files_inst/mem_reg[2]_29[30]} {cpu_inst/reg_files_inst/mem_reg[2]_29[31]}]]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:450 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {cpu_inst/reg_files_inst/mem_reg[3]_28[0]} {cpu_inst/reg_files_inst/mem_reg[3]_28[1]} {cpu_inst/reg_files_inst/mem_reg[3]_28[2]} {cpu_inst/reg_files_inst/mem_reg[3]_28[3]} {cpu_inst/reg_files_inst/mem_reg[3]_28[4]} {cpu_inst/reg_files_inst/mem_reg[3]_28[5]} {cpu_inst/reg_files_inst/mem_reg[3]_28[6]} {cpu_inst/reg_files_inst/mem_reg[3]_28[7]} {cpu_inst/reg_files_inst/mem_reg[3]_28[8]} {cpu_inst/reg_files_inst/mem_reg[3]_28[9]} {cpu_inst/reg_files_inst/mem_reg[3]_28[10]} {cpu_inst/reg_files_inst/mem_reg[3]_28[11]} {cpu_inst/reg_files_inst/mem_reg[3]_28[12]} {cpu_inst/reg_files_inst/mem_reg[3]_28[13]} {cpu_inst/reg_files_inst/mem_reg[3]_28[14]} {cpu_inst/reg_files_inst/mem_reg[3]_28[15]} {cpu_inst/reg_files_inst/mem_reg[3]_28[16]} {cpu_inst/reg_files_inst/mem_reg[3]_28[17]} {cpu_inst/reg_files_inst/mem_reg[3]_28[18]} {cpu_inst/reg_files_inst/mem_reg[3]_28[19]} {cpu_inst/reg_files_inst/mem_reg[3]_28[20]} {cpu_inst/reg_files_inst/mem_reg[3]_28[21]} {cpu_inst/reg_files_inst/mem_reg[3]_28[22]} {cpu_inst/reg_files_inst/mem_reg[3]_28[23]} {cpu_inst/reg_files_inst/mem_reg[3]_28[24]} {cpu_inst/reg_files_inst/mem_reg[3]_28[25]} {cpu_inst/reg_files_inst/mem_reg[3]_28[26]} {cpu_inst/reg_files_inst/mem_reg[3]_28[27]} {cpu_inst/reg_files_inst/mem_reg[3]_28[28]} {cpu_inst/reg_files_inst/mem_reg[3]_28[29]} {cpu_inst/reg_files_inst/mem_reg[3]_28[30]} {cpu_inst/reg_files_inst/mem_reg[3]_28[31]}]]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:454 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:455 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:456 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {cpu_inst/reg_files_inst/mem_reg[4]_27[0]} {cpu_inst/reg_files_inst/mem_reg[4]_27[1]} {cpu_inst/reg_files_inst/mem_reg[4]_27[2]} {cpu_inst/reg_files_inst/mem_reg[4]_27[3]} {cpu_inst/reg_files_inst/mem_reg[4]_27[4]} {cpu_inst/reg_files_inst/mem_reg[4]_27[5]} {cpu_inst/reg_files_inst/mem_reg[4]_27[6]} {cpu_inst/reg_files_inst/mem_reg[4]_27[7]} {cpu_inst/reg_files_inst/mem_reg[4]_27[8]} {cpu_inst/reg_files_inst/mem_reg[4]_27[9]} {cpu_inst/reg_files_inst/mem_reg[4]_27[10]} {cpu_inst/reg_files_inst/mem_reg[4]_27[11]} {cpu_inst/reg_files_inst/mem_reg[4]_27[12]} {cpu_inst/reg_files_inst/mem_reg[4]_27[13]} {cpu_inst/reg_files_inst/mem_reg[4]_27[14]} {cpu_inst/reg_files_inst/mem_reg[4]_27[15]} {cpu_inst/reg_files_inst/mem_reg[4]_27[16]} {cpu_inst/reg_files_inst/mem_reg[4]_27[17]} {cpu_inst/reg_files_inst/mem_reg[4]_27[18]} {cpu_inst/reg_files_inst/mem_reg[4]_27[19]} {cpu_inst/reg_files_inst/mem_reg[4]_27[20]} {cpu_inst/reg_files_inst/mem_reg[4]_27[21]} {cpu_inst/reg_files_inst/mem_reg[4]_27[22]} {cpu_inst/reg_files_inst/mem_reg[4]_27[23]} {cpu_inst/reg_files_inst/mem_reg[4]_27[24]} {cpu_inst/reg_files_inst/mem_reg[4]_27[25]} {cpu_inst/reg_files_inst/mem_reg[4]_27[26]} {cpu_inst/reg_files_inst/mem_reg[4]_27[27]} {cpu_inst/reg_files_inst/mem_reg[4]_27[28]} {cpu_inst/reg_files_inst/mem_reg[4]_27[29]} {cpu_inst/reg_files_inst/mem_reg[4]_27[30]} {cpu_inst/reg_files_inst/mem_reg[4]_27[31]}]]
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:458 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:459 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:460 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {cpu_inst/reg_files_inst/mem_reg[5]_26[0]} {cpu_inst/reg_files_inst/mem_reg[5]_26[1]} {cpu_inst/reg_files_inst/mem_reg[5]_26[2]} {cpu_inst/reg_files_inst/mem_reg[5]_26[3]} {cpu_inst/reg_files_inst/mem_reg[5]_26[4]} {cpu_inst/reg_files_inst/mem_reg[5]_26[5]} {cpu_inst/reg_files_inst/mem_reg[5]_26[6]} {cpu_inst/reg_files_inst/mem_reg[5]_26[7]} {cpu_inst/reg_files_inst/mem_reg[5]_26[8]} {cpu_inst/reg_files_inst/mem_reg[5]_26[9]} {cpu_inst/reg_files_inst/mem_reg[5]_26[10]} {cpu_inst/reg_files_inst/mem_reg[5]_26[11]} {cpu_inst/reg_files_inst/mem_reg[5]_26[12]} {cpu_inst/reg_files_inst/mem_reg[5]_26[13]} {cpu_inst/reg_files_inst/mem_reg[5]_26[14]} {cpu_inst/reg_files_inst/mem_reg[5]_26[15]} {cpu_inst/reg_files_inst/mem_reg[5]_26[16]} {cpu_inst/reg_files_inst/mem_reg[5]_26[17]} {cpu_inst/reg_files_inst/mem_reg[5]_26[18]} {cpu_inst/reg_files_inst/mem_reg[5]_26[19]} {cpu_inst/reg_files_inst/mem_reg[5]_26[20]} {cpu_inst/reg_files_inst/mem_reg[5]_26[21]} {cpu_inst/reg_files_inst/mem_reg[5]_26[22]} {cpu_inst/reg_files_inst/mem_reg[5]_26[23]} {cpu_inst/reg_files_inst/mem_reg[5]_26[24]} {cpu_inst/reg_files_inst/mem_reg[5]_26[25]} {cpu_inst/reg_files_inst/mem_reg[5]_26[26]} {cpu_inst/reg_files_inst/mem_reg[5]_26[27]} {cpu_inst/reg_files_inst/mem_reg[5]_26[28]} {cpu_inst/reg_files_inst/mem_reg[5]_26[29]} {cpu_inst/reg_files_inst/mem_reg[5]_26[30]} {cpu_inst/reg_files_inst/mem_reg[5]_26[31]}]]
set_property src_info {type:XDC file:1 line:461 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:462 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:463 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {cpu_inst/reg_files_inst/mem_reg[6]_25[0]} {cpu_inst/reg_files_inst/mem_reg[6]_25[1]} {cpu_inst/reg_files_inst/mem_reg[6]_25[2]} {cpu_inst/reg_files_inst/mem_reg[6]_25[3]} {cpu_inst/reg_files_inst/mem_reg[6]_25[4]} {cpu_inst/reg_files_inst/mem_reg[6]_25[5]} {cpu_inst/reg_files_inst/mem_reg[6]_25[6]} {cpu_inst/reg_files_inst/mem_reg[6]_25[7]} {cpu_inst/reg_files_inst/mem_reg[6]_25[8]} {cpu_inst/reg_files_inst/mem_reg[6]_25[9]} {cpu_inst/reg_files_inst/mem_reg[6]_25[10]} {cpu_inst/reg_files_inst/mem_reg[6]_25[11]} {cpu_inst/reg_files_inst/mem_reg[6]_25[12]} {cpu_inst/reg_files_inst/mem_reg[6]_25[13]} {cpu_inst/reg_files_inst/mem_reg[6]_25[14]} {cpu_inst/reg_files_inst/mem_reg[6]_25[15]} {cpu_inst/reg_files_inst/mem_reg[6]_25[16]} {cpu_inst/reg_files_inst/mem_reg[6]_25[17]} {cpu_inst/reg_files_inst/mem_reg[6]_25[18]} {cpu_inst/reg_files_inst/mem_reg[6]_25[19]} {cpu_inst/reg_files_inst/mem_reg[6]_25[20]} {cpu_inst/reg_files_inst/mem_reg[6]_25[21]} {cpu_inst/reg_files_inst/mem_reg[6]_25[22]} {cpu_inst/reg_files_inst/mem_reg[6]_25[23]} {cpu_inst/reg_files_inst/mem_reg[6]_25[24]} {cpu_inst/reg_files_inst/mem_reg[6]_25[25]} {cpu_inst/reg_files_inst/mem_reg[6]_25[26]} {cpu_inst/reg_files_inst/mem_reg[6]_25[27]} {cpu_inst/reg_files_inst/mem_reg[6]_25[28]} {cpu_inst/reg_files_inst/mem_reg[6]_25[29]} {cpu_inst/reg_files_inst/mem_reg[6]_25[30]} {cpu_inst/reg_files_inst/mem_reg[6]_25[31]}]]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:468 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {cpu_inst/reg_files_inst/mem_reg[7]_24[0]} {cpu_inst/reg_files_inst/mem_reg[7]_24[1]} {cpu_inst/reg_files_inst/mem_reg[7]_24[2]} {cpu_inst/reg_files_inst/mem_reg[7]_24[3]} {cpu_inst/reg_files_inst/mem_reg[7]_24[4]} {cpu_inst/reg_files_inst/mem_reg[7]_24[5]} {cpu_inst/reg_files_inst/mem_reg[7]_24[6]} {cpu_inst/reg_files_inst/mem_reg[7]_24[7]} {cpu_inst/reg_files_inst/mem_reg[7]_24[8]} {cpu_inst/reg_files_inst/mem_reg[7]_24[9]} {cpu_inst/reg_files_inst/mem_reg[7]_24[10]} {cpu_inst/reg_files_inst/mem_reg[7]_24[11]} {cpu_inst/reg_files_inst/mem_reg[7]_24[12]} {cpu_inst/reg_files_inst/mem_reg[7]_24[13]} {cpu_inst/reg_files_inst/mem_reg[7]_24[14]} {cpu_inst/reg_files_inst/mem_reg[7]_24[15]} {cpu_inst/reg_files_inst/mem_reg[7]_24[16]} {cpu_inst/reg_files_inst/mem_reg[7]_24[17]} {cpu_inst/reg_files_inst/mem_reg[7]_24[18]} {cpu_inst/reg_files_inst/mem_reg[7]_24[19]} {cpu_inst/reg_files_inst/mem_reg[7]_24[20]} {cpu_inst/reg_files_inst/mem_reg[7]_24[21]} {cpu_inst/reg_files_inst/mem_reg[7]_24[22]} {cpu_inst/reg_files_inst/mem_reg[7]_24[23]} {cpu_inst/reg_files_inst/mem_reg[7]_24[24]} {cpu_inst/reg_files_inst/mem_reg[7]_24[25]} {cpu_inst/reg_files_inst/mem_reg[7]_24[26]} {cpu_inst/reg_files_inst/mem_reg[7]_24[27]} {cpu_inst/reg_files_inst/mem_reg[7]_24[28]} {cpu_inst/reg_files_inst/mem_reg[7]_24[29]} {cpu_inst/reg_files_inst/mem_reg[7]_24[30]} {cpu_inst/reg_files_inst/mem_reg[7]_24[31]}]]
set_property src_info {type:XDC file:1 line:469 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:470 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:471 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:472 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets CLK_GEN_IBUF_BUFG]
