name: Deploy via SSH with Jump Host

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Key for GitHub → Server A
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY_TESLA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H tesla.ce.pdn.ac.lk >> ~/.ssh/known_hosts

      - name: SSH to Server A and SSH to Server B
        run: |
          ssh e19129@10.40.18.26 "cd /path/to/project && ./script.sh"
