name: Remote Script Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add known hosts (ignore failures)
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H tesla.ce.pdn.ac.lk >> ~/.ssh/known_hosts || true
          ssh-keyscan -H 10.40.18.26       >> ~/.ssh/known_hosts || true

      - name: Run script on remote server through jump host
        run: |
          ssh -o ProxyJump=e19129@tesla.ce.pdn.ac.lk \
              e19129@10.40.18.26 'bash -l ~/path/to/script.sh'
