# .github/workflows/ssh-tesla-ls.yml
name: SSH into Tesla and List

on:
  push:
    branches: [main]
  workflow_dispatch: # allow manual trigger

jobs:
  ls-tesla:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (not strictly needed here)
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Add tesla to known_hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H tesla.ce.pdn.ac.lk >> $HOME/.ssh/known_hosts || true
          chmod 600 $HOME/.ssh/known_hosts

      - name: SSH into Tesla and ls
        run: |
          ssh -o StrictHostKeyChecking=yes \
              e19129@tesla.ce.pdn.ac.lk 'ls -la ~'
