# .github/workflows/ssh-tesla-run-target.yml
name: SSH into Tesla and Run Target Script

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-on-tesla:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (not strictly needed)
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Add tesla to known_hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H tesla.ce.pdn.ac.lk >> $HOME/.ssh/known_hosts || true
          chmod 600 $HOME/.ssh/known_hosts

      - name: SSH into Tesla and run run_on_target.sh
        run: |
          ssh -o StrictHostKeyChecking=yes \
              e19129@tesla.ce.pdn.ac.lk \
              'cd ~/riscv_pipeline && ./run_on_target.sh'
