name: Remote Script Runner

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa

      - name: Add known hosts
        run: |
          mkdir -p $HOME/.ssh
          ssh-keyscan -H tesla.ce.pdn.ac.lk >> $HOME/.ssh/known_hosts || true
          ssh-keyscan -H 10.40.18.26      >> $HOME/.ssh/known_hosts || true
          chmod 600 $HOME/.ssh/known_hosts

      - name: Run remote script via jump host
        run: |
          ssh -o ProxyJump=e19129@tesla.ce.pdn.ac.lk \
              e19129@10.40.18.26 'bash -l ~/path/to/script.sh'
